---
- name: Install ELK with Docker
  hosts: elk
  become: true
  tasks:

    - name: Set memory
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present

    - name: Install Docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Install Python Docker Module
      pip:
        name: docker
        state: present

    - name: Install sebp/elk:761
      docker_container:
        name: elk
        image: sebp/elk:761
        restart_policy: always
        published_ports: 
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Make sure docker is running
      systemd:
        name: docker
        enabled: yes
